apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: neptune

resources:
  - namespace.yaml
  - postgres-secret.yaml
  - postgres-config.yaml
  - postgres-statefulset.yaml
  - minio-secret.yaml
  - minio-config.yaml
  - minio-statefulset.yaml
  - ollama-deployment.yaml
  - backend-deployment.yaml
  - indexer-deployment.yaml
  - ingress.yaml
  - migrate-job.yaml
